# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/audio_spoof.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/audio_spoof.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/audio_spoof.proto\x12\x0b\x61udio_spoof\"*\n\x0ePredictRequest\x12\x18\n\x10\x61udio_chunk_data\x18\x01 \x01(\x0c\" \n\x0fPredictResponse\x12\r\n\x05logit\x18\x01 \x01(\x02\x32_\n\x12\x41udioSpoofDetector\x12I\n\x0cPredictChunk\x12\x1b.audio_spoof.PredictRequest\x1a\x1c.audio_spoof.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.audio_spoof_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=40
  _globals['_PREDICTREQUEST']._serialized_end=82
  _globals['_PREDICTRESPONSE']._serialized_start=84
  _globals['_PREDICTRESPONSE']._serialized_end=116
  _globals['_AUDIOSPOOFDETECTOR']._serialized_start=118
  _globals['_AUDIOSPOOFDETECTOR']._serialized_end=213
# @@protoc_insertion_point(module_scope)
