# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_analyzer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'audio_analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61udio_analyzer.proto\x12\raudioanalyzer\"J\n\x13\x41nalyzeAudioRequest\x12\x19\n\x11minio_bucket_name\x18\x01 \x01(\t\x12\x18\n\x10minio_object_key\x18\x02 \x01(\t\"m\n\x14\x41udioChunkPrediction\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x1a\n\x12start_time_seconds\x18\x03 \x01(\x02\x12\x18\n\x10\x65nd_time_seconds\x18\x04 \x01(\x02\"g\n\x14\x41nalyzeAudioResponse\x12\x38\n\x0bpredictions\x18\x01 \x03(\x0b\x32#.audioanalyzer.AudioChunkPrediction\x12\x15\n\rerror_message\x18\x02 \x01(\t2h\n\rAudioAnalysis\x12W\n\x0c\x41nalyzeAudio\x12\".audioanalyzer.AnalyzeAudioRequest\x1a#.audioanalyzer.AnalyzeAudioResponseB,Z*example.com/auth_service/gen/audioanalyzerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*example.com/auth_service/gen/audioanalyzer'
  _globals['_ANALYZEAUDIOREQUEST']._serialized_start=39
  _globals['_ANALYZEAUDIOREQUEST']._serialized_end=113
  _globals['_AUDIOCHUNKPREDICTION']._serialized_start=115
  _globals['_AUDIOCHUNKPREDICTION']._serialized_end=224
  _globals['_ANALYZEAUDIORESPONSE']._serialized_start=226
  _globals['_ANALYZEAUDIORESPONSE']._serialized_end=329
  _globals['_AUDIOANALYSIS']._serialized_start=331
  _globals['_AUDIOANALYSIS']._serialized_end=435
# @@protoc_insertion_point(module_scope)
