# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_spoof.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'audio_spoof.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61udio_spoof.proto\x12\x0b\x61udio_spoof\"[\n\x10\x41udioDataRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x18\n\x10minio_object_key\x18\x02 \x01(\t\x12\x19\n\x11original_filename\x18\x03 \x01(\t\" \n\x0f\x43hunkPrediction\x12\r\n\x05score\x18\x01 \x01(\x02\"\xf0\x01\n\x16\x41udioDetectionResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12T\n\x11\x63hunk_predictions\x18\x02 \x03(\x0b\x32\x39.audio_spoof.AudioDetectionResponse.ChunkPredictionsEntry\x12\x15\n\rerror_message\x18\x03 \x01(\t\x1aU\n\x15\x43hunkPredictionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.audio_spoof.ChunkPrediction:\x02\x38\x01\x32\x64\n\x0e\x41udioDetection\x12R\n\x0cProcessAudio\x12\x1d.audio_spoof.AudioDataRequest\x1a#.audio_spoof.AudioDetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_spoof_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIODETECTIONRESPONSE_CHUNKPREDICTIONSENTRY']._loaded_options = None
  _globals['_AUDIODETECTIONRESPONSE_CHUNKPREDICTIONSENTRY']._serialized_options = b'8\001'
  _globals['_AUDIODATAREQUEST']._serialized_start=34
  _globals['_AUDIODATAREQUEST']._serialized_end=125
  _globals['_CHUNKPREDICTION']._serialized_start=127
  _globals['_CHUNKPREDICTION']._serialized_end=159
  _globals['_AUDIODETECTIONRESPONSE']._serialized_start=162
  _globals['_AUDIODETECTIONRESPONSE']._serialized_end=402
  _globals['_AUDIODETECTIONRESPONSE_CHUNKPREDICTIONSENTRY']._serialized_start=317
  _globals['_AUDIODETECTIONRESPONSE_CHUNKPREDICTIONSENTRY']._serialized_end=402
  _globals['_AUDIODETECTION']._serialized_start=404
  _globals['_AUDIODETECTION']._serialized_end=504
# @@protoc_insertion_point(module_scope)
