# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_analyzer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'audio_analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61udio_analyzer.proto\x12\raudioanalyzer\"J\n\x13\x41nalyzeAudioRequest\x12\x19\n\x11minio_bucket_name\x18\x01 \x01(\t\x12\x18\n\x10minio_object_key\x18\x02 \x01(\t\"\xac\x01\n\x14\x41nalyzeAudioResponse\x12I\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x34.audioanalyzer.AnalyzeAudioResponse.PredictionsEntry\x12\x15\n\rerror_message\x18\x02 \x01(\t\x1a\x32\n\x10PredictionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32h\n\rAudioAnalysis\x12W\n\x0c\x41nalyzeAudio\x12\".audioanalyzer.AnalyzeAudioRequest\x1a#.audioanalyzer.AnalyzeAudioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEAUDIORESPONSE_PREDICTIONSENTRY']._loaded_options = None
  _globals['_ANALYZEAUDIORESPONSE_PREDICTIONSENTRY']._serialized_options = b'8\001'
  _globals['_ANALYZEAUDIOREQUEST']._serialized_start=39
  _globals['_ANALYZEAUDIOREQUEST']._serialized_end=113
  _globals['_ANALYZEAUDIORESPONSE']._serialized_start=116
  _globals['_ANALYZEAUDIORESPONSE']._serialized_end=288
  _globals['_ANALYZEAUDIORESPONSE_PREDICTIONSENTRY']._serialized_start=238
  _globals['_ANALYZEAUDIORESPONSE_PREDICTIONSENTRY']._serialized_end=288
  _globals['_AUDIOANALYSIS']._serialized_start=290
  _globals['_AUDIOANALYSIS']._serialized_end=394
# @@protoc_insertion_point(module_scope)
