# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import audio_analyzer_pb2 as audio__analyzer__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in audio_analyzer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioAnalysisStub(object):
    """Сервис для анализа аудио
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeAudio = channel.unary_unary(
                '/audioanalyzer.AudioAnalysis/AnalyzeAudio',
                request_serializer=audio__analyzer__pb2.AnalyzeAudioRequest.SerializeToString,
                response_deserializer=audio__analyzer__pb2.AnalyzeAudioResponse.FromString,
                _registered_method=True)


class AudioAnalysisServicer(object):
    """Сервис для анализа аудио
    """

    def AnalyzeAudio(self, request, context):
        """Метод для обработки аудиофайла из MinIO
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioAnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeAudio,
                    request_deserializer=audio__analyzer__pb2.AnalyzeAudioRequest.FromString,
                    response_serializer=audio__analyzer__pb2.AnalyzeAudioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audioanalyzer.AudioAnalysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('audioanalyzer.AudioAnalysis', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioAnalysis(object):
    """Сервис для анализа аудио
    """

    @staticmethod
    def AnalyzeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audioanalyzer.AudioAnalysis/AnalyzeAudio',
            audio__analyzer__pb2.AnalyzeAudioRequest.SerializeToString,
            audio__analyzer__pb2.AnalyzeAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
